#!/bin/bash

cd ~
# Added: Capture the absolute user home path immediately to avoid /root issues in crontab
USER_HOME=$(pwd)
set -e

echo Please enter your password to proceed with the setup:
sudo -v

echo Now configuring swappiness.
if grep -q "vm.swappiness=10" /etc/sysctl.conf; then
    echo "Swappiness already configured. Skipping."
else
    sudo sysctl vm.swappiness=10
    echo "vm.swappiness=10" | sudo tee -a /etc/sysctl.conf
fi
echo Swappiness configured.

echo Now installing Log2Ram to reduce SD card wear
sudo apt install -y curl gnupg wget
echo "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ bookworm main" | sudo tee /etc/apt/sources.list.d/azlux.list
sudo wget -O /usr/share/keyrings/azlux-archive-keyring.gpg https://azlux.fr/repo.gpg
sudo apt update
sudo apt install -y log2ram
sudo systemctl enable log2ram
sudo systemctl start log2ram
echo Log2Ram installation complete.

mkdir -p ./xmrig
cd ./xmrig
# Temporarely straight up using Gemini generated code
echo ">> Installing build dependencies..."
# 安裝編譯所需的依賴庫 (libuv, ssl, hwloc 是必須的)
sudo apt update
sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

echo ">> Fetching latest XMRig source..."
# Modified: Used USER_HOME instead of HOME
SRC_DIR="$USER_HOME/xmrig-src"
# Modified: Used USER_HOME instead of HOME
DEST_DIR="$USER_HOME/xmrig"

# 如果原始碼資料夾不存在就 Clone，存在就 Pull 更新
if [ ! -d "$SRC_DIR" ]; then
    git clone https://github.com/xmrig/xmrig.git "$SRC_DIR"
else
    cd "$SRC_DIR" && git pull
fi

# 進入編譯目錄
mkdir -p "$SRC_DIR/build"
cd "$SRC_DIR/build"

echo ">> Compiling XMRig (Latest)... This may take a while."
# 配置 CMake
cmake ..
# 開始編譯 (使用所有 CPU 核心加速)
make -j$(nproc)

# 將編譯好的執行檔複製到目標資料夾
echo ">> Installing binary..."
mkdir -p "$DEST_DIR"
cp xmrig "$DEST_DIR/xmrig"

echo "XMRig build complete."
# ^ Generated by Gemini
cat <<EOF > $USER_HOME/start-xmrig.sh
#!/bin/bash
echo "[XMRIG] Waiting for internet connection..."
count=0
while ! ping -c 1 8.8.8.8 &> /dev/null; do
    sleep 5
    ((count++))
    if [ \$count -ge 12 ]; then
        break
    fi
done
$USER_HOME/xmrig/xmrig -o stratum+ssl://rx.unmineable.com:4444 -k -u [coin]:[address].unmineable_miner_RPiSub#elce-axze --http-port=60070 -a rx
EOF
chmod +x $USER_HOME/start-xmrig.sh
if ! sudo crontab -l 2>/dev/null | grep -q "start-xmrig.sh"; then
    # Modified: Used USER_HOME variables for correct crontab paths
    (sudo crontab -l 2>/dev/null; echo "@reboot $USER_HOME/start-xmrig.sh >> $USER_HOME/xmrig.log 2>&1") | sudo crontab -
    echo "Auto-start added to Root Crontab."
else
    echo "Crontab already configured. Skipping."
fi
echo "Execution script generated."

cd
echo "Now installing Cockpit"
. /etc/os-release
sudo apt install -y -t ${VERSION_CODENAME}-backports cockpit || sudo apt install -y cockpit
echo Cockpit installation complete.
echo "You can access Cockpit by navigating to http://[your_raspberry_pi_ip]:9090. Your Raspberry Pi's IP address is"
hostname -I | awk '{print $1}'